# Generated by Django 5.1 on 2024-08-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha_nacimiento', models.DateField(max_length=20, verbose_name='Fecha de Nacimiento')),
                ('correo', models.CharField(max_length=70, verbose_name='Correo')),
                ('contrasena', models.CharField(max_length=50, verbose_name='Contrasena')),
                ('especialidades', models.TextField(max_length=100, verbose_name='Especialidades')),
                ('habilidades', models.CharField(max_length=100, verbose_name='Habilidades')),
                ('experiencia', models.CharField(choices=[('>4 años', 'Más de 4 años'), ('<4 años', 'Menos de 4 años'), ('ninguna', 'Ninguna')], max_length=70, verbose_name='Experiencia')),
            ],
        ),
        migrations.DeleteModel(
            name='CandidatoDB',
        ),
        migrations.RemoveField(
            model_name='empleadordb',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='empleadordb',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='empleadordb',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='empleadordb',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='empleadordb',
            name='tipo',
        ),
    ]
