# Generated by Django 5.1 on 2024-08-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_usuariodb_delete_candidatodb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Tópico')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'db_table': 'Topicos',
            },
        ),
        migrations.AlterModelOptions(
            name='usuariodb',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelTable(
            name='usuariodb',
            table='Usuarios',
        ),
    ]
