# Generated by Django 5.1 on 2024-08-24 21:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_habilidades_usuariopersonalizado_delete_topico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertadb',
            name='promedio_calificacion',
            field=models.FloatField(default=0.0, verbose_name='Calificación Promedio'),
        ),
        migrations.AddField(
            model_name='resenasdb',
            name='empleador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App1.empleadordb'),
        ),
        migrations.AlterField(
            model_name='empleadordb',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='resenasdb',
            name='calificacion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Calificación'),
        ),
    ]
