# Generated by Django 5.1 on 2024-08-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_ofertadb_promedio_calificacion_resenasdb_empleador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertadb',
            old_name='Habilidades',
            new_name='habilidades',
        ),
    ]
