# Generated by Django 5.1 on 2024-08-24 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_rename_habilidades_ofertadb_habilidades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmpleadorDB',
            new_name='EmpresaDB',
        ),
        migrations.AlterModelOptions(
            name='empresadb',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.RenameField(
            model_name='resenasdb',
            old_name='empleador',
            new_name='empresa',
        ),
        migrations.AlterModelTable(
            name='empresadb',
            table='Empresas',
        ),
    ]
