# Generated by Django 5.1 on 2024-08-25 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_rename_empleadordb_empresadb_alter_empresadb_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenasdb',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='usuabiodb',
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='correo',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='nombre',
            field=models.CharField(default='Nombre Predeterminado', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ofertadb',
            name='topicos',
            field=models.CharField(choices=[('PR', 'Programacion'), ('SG', 'Seguridad'), ('IA', 'Inteligencia Artificial'), ('BD', 'Bases de Datos'), ('DW', 'Diseño Web')], max_length=100, verbose_name='Topicos'),
        ),
        migrations.DeleteModel(
            name='UsuarioDB',
        ),
    ]
