# Generated by Django 5.1 on 2024-08-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_alter_resenasdb_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertadb',
            name='promedio_calificacion',
            field=models.FloatField(verbose_name='Calificación Promedio'),
        ),
    ]
