# Generated by Django 5.1 on 2024-08-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_alter_ofertadb_promedio_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
