# Generated by Django 5.1 on 2024-08-25 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_alter_usuariopersonalizado_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertadb',
            name='fecha_limite',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Límite'),
        ),
    ]
